version: "3.9"

services:
  weather-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: weather-web
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app